# @see https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html#examples
---
- hosts: sherman
  become: true
  roles:
    - common
    - ufw
  vars:
    ufw_rules:
      # Set loggin
      - logging: "full"
      # Allow OpenSSH
      - rule: allow
        name: OpenSSH
      # Allow all access to tcp port 80
      - rule: allow
        to_port: '80'
        proto: tcp
      # Allow all access to tcp port 4000 for Jekyll site
      - rule: allow
        to_port: '4000'
        proto: tcp
      # Allow all access to tcp port 35729 for Jekyll live-reload
      - rule: allow
        to_port: '35729'
        proto: tcp
    # Manage the configuration file
    ufw_manage_config: true
    # Configuration object passed to the configuration file
    ufw_config:
      IPV6: "no"
      DEFAULT_INPUT_POLICY: DROP
      DEFAULT_OUTPUT_POLICY: ACCEPT
      DEFAULT_FORWARD_POLICY: DROP
      DEFAULT_APPLICATION_POLICY: SKIP
      MANAGE_BUILTINS: "no"
      IPT_SYSCTL: /etc/ufw/sysctl.conf
      IPT_MODULES: ""
