# This is a playbook that uses the virt module directly,
# unlike others in this project that use them indirectly, through roles.
# To run it, do `ansible-playbook virt.yml --ask-become-pass`
# An example of an ad-hoc statement, using the virt module:
# `ansible host -m virt -m "name=alpha command=status`
---
- name: Manage libvirt networks
  hosts: localhost

  tasks:
    - name: List available networks
      community.libvirt.virt_net:
        command: list_nets
      register: libvirt_nets

    - name: Print the list
      ansible.builtin.debug:
        var: libvirt_nets

    - name: Get XML data of a specified network
      community.libvirt.virt_net:
        command: get_xml
        name: host-bridge
      register: host_bridge_xml
    
    - name: Print host-bridge network XML
      ansible.builtin.debug:
        var: host_bridge_xml
