- name: 'Install the Apache Webserver'
  ansible.builtin.package:
    name: 'httpd'
    state: 'present'
- name: 'Ensure web server is running an enabled'
  ansible.builtin.service:
    name: 'httpd'
    state: 'started'
    enabled: true
- name: 'Copy some web content'
  ansible.builtin.copy:
    dest: '/var/www/html/index.html'
    content: 'This is a simple webserver'
