- name: Ensure the 'ansible' user exists
  ansible.builtin.user:
    name: ansible
    state: present
    createhome: true
- name: Copy ssh key to remote host
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
- name: Make ansible a sudoer
  ansible.builtin.copy:
    src: ans
    dest: /etc/sudoers.d/
    mode: "0440"
    validate: /usr/sbin/visudo -csf %s
- name: Ensure the 'ansible' user exists
  ansible.builtin.user:
    name: ansible
    state: present
    createhome: true
