- name: Update CentOS (using yum)
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_only: true
  when: ansible_os_family == 'RedHat'

- name: Install a list of packages with a list variable
  ansible.builtin.yum:
    name: "{{ common_packages }}"
    update_only: true
  when: ansible_os_family == 'RedHat'

- name: Update Ubuntu (using apt)
  ansible.builtin.apt:
    only_upgrade: 'yes'
  when: ansible_os_family == 'Debian'
