---
- name: Establish a base configuration for all hosts.
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Copy /etc/hosts template
      ansible.builtin.template:
        src: ../templates/hosts_template.j2
        dest: /etc/hosts
    # Configure as NTP clients
    - name: Allow ntp through firewall
      shell: firewall-cmd --zone=public --add-port=123/udp --permanent
    - name: Reload firewall
      shell: firewall-cmd --reload
    