- name: Ansible user
  ansible.builtin.import_tasks: ansible_user.yml

- name: Configure /etc/hosts
  ansible.builtin.import_tasks: etc_hosts.yml

- name: Update Linux
  ansible.builtin.import_tasks: linux_update.yml

- name: Manage the chrony timeserver
  ansible.builtin.import_tasks: chrony.yml
