- name: Ansible user
  import_tasks: ansible_user.yml

- name: Configure /etc/hosts
  import_tasks: etc_hosts.yml

- name: Update Linux
  import_tasks: linux_update.yml

- name: Install the correct web server for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'