    - name: Update CentOS (using yum)
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'
    - name: Update Ubuntu (using apt)
      ansible.builtin.apt:
        upgrade: 'yes'
      when: ansible_os_family == 'Debian'
