- name: Get a list of all libvirt guests
  community.libvirt.virt:
    command: list_vms
  register: libvirt_guests

- name: Display the list of all libvirt guests
  debug:
    var: libvirt_guests

- name: List all running vms 
  community.libvirt.virt: 
    command: list_vms
    state: running 
  register: running_vms

- name: Print list
  debug:
    var: running_vms

#    - name: Start mirko
#      community.libvirt.virt:
#        command: start
#        name: mirko
#      register: mirko_status

#    - name: Check mirko's status 
#      debug:
#        var: mirko_status
      